---
# tasks file for cron




# Set up a system Timer to backup the contents of your /etc directory. 
# https://wiki.archlinux.org/index.php/Systemd/Timers

You need to create two files: one for service, other for timer with same name.

example:

/etc/systemd/system/test.service

[Unit]
Description=test job

[Service]
Type=oneshot
ExecStart=/bin/bash /tmp/1.sh

/etc/systemd/system/test.timer

[Unit]
Description=test

[Timer]
OnUnitActiveSec=10s
OnBootSec=10s

[Install]
WantedBy=timers.target
after that reload the systemd using command systemctl daemon-reload and start your timer by systemctl start test.timer, or enable them by default.

test content of 1.sh

#!/bin/bash
echo `date` >> /tmp/2



# Backup Your /etc Directory
# https://scottlinux.com/2015/08/07/backup-your-etc-directory-with-daily-cron-task/