---
# tasks file for wordPress




# Install mysql or mariadb
#yum install mysql
yum install mariadb-server
systemctl start mariadb
systemctl enable mariadb

# Use this command to run the security script
mysql_secure_installation

# Create a new database that WordPress can control.
CREATE DATABASE wordpress;

# Make SQL User
CREATE USER wordpressuser@localhost IDENTIFIED BY 'password';

# nk the two components together by granting our user access to the database.
CREATE USER wordpress@localhost IDENTIFIED BY 'password';

# Flush the privileges so that MySQL knows about the recent privilege changes 
FLUSH PRIVILEGES;

# Install PHP and dependent package (PHP 5.4.16)
yum install php 

# resize images to create thumbnails
yum install php-gd

# Restart Apache so that it recognizes the new module
service httpd restart

wget http://wordpress.org/latest.tar.gz

tar xzvf latest.tar.gz.

# (Optional) We can transfer our WordPress 
# files there with rsync, which will preserve the files' 
# default permissions:)
sync -avP ~/wordpress/ /var/www/html/


# add a folder for WordPress to store uploaded files.
mkdir /var/www/html/wp-content/uploads

# Assign the correct ownership and permissions to 
# WordPress files and folders.
sudo chown -R apache:apache /var/www/html/*


# Resources: 
# Install MariaDB 
# https://www.digitalocean.com/community/tutorials/how-to-install-mariadb-on-centos-7
# Install WordPress on CentOS 7
# https://www.digitalocean.com/community/tutorials/how-to-install-wordpress-on-centos-7
# 
#